<?php
$title = 'My albums';
$this->headTitle($title);

$this->headScript()->appendFile('/js/underscore.js', 'text/javascript');
?>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    </script>

<link rel="stylesheet" href="css/album/update-artist.css" type="text/css">
<link rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
      crossorigin="anonymous">

<h1><?= $this->escapeHtml($title) ?></h1>

<div class="alertBox"></div>
<br>

<p>
  <a href="<?= $this->url('album',['action' => 'add'])?>" class="btn btn-success">
      Add new album</a>
</p>

<table class="table">
  <tr>
    <th style="text-align:center">Album Cover</th>
    <th style="text-align:center">Title</th>
    <th style="text-align:center">Artist</th>
  </tr>

<?php
foreach($this->paginator as $album):
?>

<tr>
  <?php if ($album->imagepath && file_exists('./public' . $album->imagepath)):?>
  <td style="text-align:center">
    <?php echo '<img src="' . $album->imagepath .
        '" alt="no image" height="50", width="50">'?>
  </td>
  <?php else :?>
  <td style="text-align:center;">
    <?php echo '<img src="./album_cover/default.jpg"
        alt="no image" height="30", width="50">'?>
  </td>
  <?php endif;?>

  <td style="text-align:center">
    <a href="<?=$this->url('album', ['action' => 'detail', 'id' => $album->id])?>">
        <?= $this->escapeHtml($album->title)?>
    </a>
  </td>

  <td class="artistCell" style="text-align:center" data-id="<?= $album->id; ?>">
      <span class="artistSpan"><?= $this->escapeHtml($album->artist)?></span>
      <a href="#" class="editArtist"><i class="far fa-edit"></i></a>
  </td>
<?php endforeach;?>
</table>

<?=
$this->paginationControl(
    $this->paginator,
    'sliding',
    'partial/paginator',
    ['route' => 'album']
)
?>

<div style="float:right">
  <a href="<?= $this->url('album',['action' => 'down'])?>" class="btn btn-info">
    Download Albums as CSV</a>
</div>

<?php
$this->headScript()->appendFile('/js/application/notifier.js', 'text/javascript');
$this->headScript()->appendFile('/js/application/ajax.js', 'text/javascript');
$this->headScript()->appendFile('/js/album/view.js', 'text/javascript');
$this->headScript()->appendFile('/js/album/page.js', 'text/javascript');
?>
