<?php
$title = 'Add new song';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title)?></h1>

<?php
$song = $form->get('song_title');
$song->setAttribute('class', 'form-control');
$song->setAttribute('placeholder', 'Song title');

$submit = $form->get('submitbtn');
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
  <?= $this->formLabel($song)?>
  <?= $this->formElement($song)?>
  <?= $this->formElementErrors()->render($song, ['class' => 'help-block'])?>
</div>

<?php echo $this->formRow($form->get('songpath')) ?>
<br><br>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
