<?php
$title = 'Delete song';
$this->headTitle($title);

$url = $this->url(
    'album/deletesong',
    ['id' => $album->id, 'song_id' => $song->id]
);
?>

<h1><?= $this->escapeHtml($title)?></h1>

<p>
  Are you sure that you want to delete
    "<?= $this->escapeHtml($song->song_title)?>" from album
    "<?= $this->escapeHtml($album->title)?>" by
    "<?= $this->escapeHtml($album->artist)?>"?
</p>

<form action="<?= $url ?>" method="post">
  <div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $song->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
  </div>
</form>
